# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U word_forms 
    - name: Add verb endings
      run: |  
        python scripts/verbendings.py
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional, but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Updating Verb Endings
        # Optional commit user and author settings
        commit_user_name: Dhuryn Action 
        commit_user_email: daniel.v.huryn@gmail.com 
        commit_author: DHuryn <daniel.v.huryn@gmail.com>

       

        # Optional. Used by `git-add`
        # See https://git-scm.com/docs/git-add#_options
        add_options: '-A'
